#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"
skip_branches='^(master|staging)$'

if [[ $branch =~ $skip_branches ]]; then
    echo "Skipping auto format"
    exit 0
fi

npx lint-staged
exit 0